# SPDX-FileCopyrightText: 2025 Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0

- id: check-encoding
  name: Check file encoding
  description: Validate that files are in the correct encoding (default UTF-8)
  entry: check-encoding
  language: python
  types: [text]
  args: []
